### ISSUE TITLE
Clear versioning scheme & release methodology

### ISSUE THREAD

**Issue by DavidPHirsch** [open-feature/toc-proposal#5]
Hi @Kavindu-Dodan and @toddbaert 
could you have a look at the "Clear versioning scheme & release methodology" section of the doc and try to add some information?

**Comment by toddbaert** [comment]
> Clear versioning scheme & release methodology

I searched this repo for this phrase and it returned no results (except this issue). Could you add a permalink to what you'd like reviewed?

**Comment by DavidPHirsch** [comment]
sorry, https://github.com/open-feature/toc-proposal/blob/main/proposals/incubation/openfeature.md
